version: "3.9"

services:
  simplyfly-frontend:
    build: .
    container_name: simplyfly-frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true